elabo/config/routes.rb
Rails.application.routes.draw do
  get 'exams/index'
  get 'exams/new'
  get 'exams/edit'
  get 'exams/show'
  devise_for :users

  # Routes pour les patients
  get 'patients/dashboard', to: 'patients#dashboard', as: 'patient_dashboard'
  get 'patients/schedule', to: 'patients#schedule', as: 'patient_schedule'
  get 'patients/exams/:laboratory_id', to: 'patients#exams', as: 'patient_exams'
  get 'patients/appointments', to: 'patients#appointments', as: 'patient_appointments'

  # resources :appointments only[:create]

  # Routes pour les laborantins
  get 'dashboard', to: 'laborantins#dashboard', as: 'laborantin_dashboard'

  resources :laboratories do
      member do
        get 'exams', to: 'laboratories#exams', as: 'laboratory_exams'
      end
      resources :exams do
        resources :appointments do
          member do
            get 'confirm', to: 'appointments#confirm', as: 'confirm'
            get 'reject', to: 'appointments#reject', as: 'reject'
          end
        end
      end
  end

  # Profil utilisateur
  resource :profile, only: [:show, :edit, :update]

  # Page de contact
  get 'contact', to: 'contacts#index'

  # Route racine
  root 'main#index'

  # Route pour le profil utilisateur
  resources :users, only: [:show]
end

elabo/app/models/appointment.rb
class Appointment < ApplicationRecord
  belongs_to :user
  belongs_to :exam
  validates :date, presence: true



  enum status: { pending: 'pending', confirmed: 'confirmed', cancelled: 'cancelled' }

  validates :status, inclusion: { in: statuses.keys }
end

elabo/app/helpers/appointments_helper.rb
module AppointmentsHelper
end

elabo/app/views/appointments/appointments.html.erb
<h1>Mes rendez-vous</h1>

<ul>
  <% @appointments.each do |appointment| %>
    <li>
      Examen : <%= appointment.exam.name %> -
      Laboratoire : <%= appointment.exam.laboratory.name %> -
      Date : <%= appointment.date.strftime('%d %B %Y, %H:%M') %>
    </li>
  <% end %>
</ul>

elabo/app/views/appointments/index.html.erb
<h1>Mes Réservations</h1>

<div class="card-deck">
  <% @appointments.each do |appointment| %>
    <div class="card mb-4">
      <div class="card-body">
        <h5 class="card-title">Réservation pour <%= appointment.exam.nom %></h5>
        <p><strong>Patient :</strong> <%= appointment.patient.name %></p> <!-- Nom du patient -->
        <p><strong>Date :</strong> <%= appointment.date.strftime("%d/%m/%Y à %H:%M") %></p>
        <p><strong>Status :</strong> <%= appointment.status %></p>

        <!-- Détails de la réservation -->
        <h6>Détails de la réservation :</h6>
        <ul>
          <li><strong>Condition Préalable :</strong> <%= appointment.exam.conditionPrealable %></li>
          <li><strong>Précautions :</strong> <%= appointment.exam.precaution %></li>
          <li><strong>Montant :</strong> <%= appointment.exam.montant %> €</li>
        </ul>

        <!-- Actions pour confirmer ou rejeter la réservation -->
        <div class="mt-3">
          <%= link_to 'Confirmer', confirm_appointment_path(appointment), method: :patch, class: 'btn btn-success', data: { confirm: 'Êtes-vous sûr de vouloir confirmer cette réservation ?' } %>
          <%= link_to 'Rejeter', reject_appointment_path(appointment), method: :delete, data: { confirm: 'Êtes-vous sûr de vouloir rejeter cette réservation ?' }, class: 'btn btn-danger' %>
        </div>
      </div>
    </div>
  <% end %>
</div>

elabo/app/views/appointments/new.html.erb
<div class="container">
  <%= form_with(model: @appointment, url: laboratory_exam_appointments_path(@laboratory, @exam), local: true) do |form| %>
      <% if @appointment.errors.any? %>
      <div class="alert alert-danger">
        <h4>Erreurs :</h4>
        <ul>
          <% @appointment.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
      </div>
      <% end %>

    <div class="form-group my-5">
      <%= form.label :date, "Date et Heure" %>
      <%= form.datetime_local_field :date, class: 'form-control', placeholder: 'YYYY-MM-DD HH:MM' %>
    </div>
    <!-- Champ caché pour le statut -->
    <%= form.hidden_field :status, value: 'pending' %>

    <div class="form-group my-5">
      <%= form.submit 'Réserver', class: 'btn btn-primary' %>
    </div>
  <% end %>
</div>

elabo/app/views/appointments/show.html.erb
<div class="container">
      <p>Statut du rendez-vous : <%= @appointment.status %></p>

    <% if @appointment.pending? %>
      <%= link_to 'Confirmer ce rendez-vous', confirm_appointment_path(@appointment), method: :patch, class: 'btn btn-primary' %>
      <%= link_to 'Annuler ce rendez-vous', cancel_appointment_path(@appointment), method: :patch, class: 'btn btn-danger' %>
    <% elsif @appointment.confirmed? %>
      <p>Ce rendez-vous est confirmé.</p>
    <% elsif @appointment.cancelled? %>
      <p>Ce rendez-vous a été annulé.</p>
    <% end %>
</div>