elabo/config/routes.rb
Rails.application.routes.draw do
  get 'exams/index'
  get 'exams/new'
  get 'exams/edit'
  get 'exams/show'
  devise_for :users

  # Routes pour les patients
  get 'patients/dashboard', to: 'patients#dashboard', as: 'patient_dashboard'
  get 'patients/schedule', to: 'patients#schedule', as: 'patient_schedule'
  get 'patients/exams/:laboratory_id', to: 'patients#exams', as: 'patient_exams'
  get 'patients/appointments', to: 'patients#appointments', as: 'patient_appointments'

  # resources :appointments only[:create]

  # Routes pour les laborantins
  get 'dashboard', to: 'laborantins#dashboard', as: 'laborantin_dashboard'

  resources :laboratories do
      member do
        get 'exams', to: 'laboratories#exams', as: 'laboratory_exams'
      end
      resources :exams do
        resources :appointments do
          member do
            get 'confirm', to: 'appointments#confirm', as: 'confirm'
            get 'reject', to: 'appointments#reject', as: 'reject'
          end
        end
      end
  end

  # Profil utilisateur
  resource :profile, only: [:show, :edit, :update]

  # Page de contact
  get 'contact', to: 'contacts#index'

  # Route racine
  root 'main#index'

  # Route pour le profil utilisateur
  resources :users, only: [:show]
end

elabo/app/controllers/laborantins_controller.rb
class LaborantinsController < ApplicationController
  before_action :authenticate_user!
  before_action :ensure_laborantin


  def dashboard
    @laborantin = current_user

    # Récupérer tous les laboratoires associés au laborantin
    @laboratories = @laborantin.laboratories

    # Récupérer les examens associés aux laboratoires du laborantin
    @exams = @laboratories.joins(:exams).distinct # Utilisation de joins pour récupérer les examens uniques

    # Récupérer les réservations associées aux examens des laboratoires du laborantin
    # Compte le nombre total de réservations en attente liées aux laboratoires du laborantin
    @appointments = Appointment.joins(exam: :laboratory)
                                  .where(laboratories: { id: @laborantin.laboratories.pluck(:id)}, status: 'pending' )

    @laboratories_count = @laboratories.count # Compte le nombre de laboratoires
    @exams_count = @exams.count # Compte le nombre d'examens différents
    @appointments_count = @appointments.count # Compte le nombre de réservations en attente
  end


  def manage_laboratory
    @laboratory = Laboratory.find(params[:id])
  end

  private

  def ensure_laborantin
    redirect_to root_path unless current_user.laborantin?
  end
end

elabo/app/helpers/laborantins_helper.rb
module LaborantinsHelper
end

elabo/app/views/laborantins/dashboard.html.erb
<div class="container my-5">
  <h1>Tableau de Bord</h1>

  <div class="row">
    <!-- Carte pour le nombre de laboratoires -->
    <div class="col-md-4">
      <div class="card text-center mb-4">
        <div class="card-header">
          Nombre de Laboratoires
        </div>
        <div class="card-body">
          <h5 class="card-title"><%= @laboratories_count %></h5>
        </div>
      </div>
    </div>

    <!-- Carte pour le nombre total d'examens différents -->
    <div class="col-md-4">
      <div class="card text-center mb-4">
        <div class="card-header">
          Nombre Total d'Examens
        </div>
        <div class="card-body">
          <h5 class="card-title"><%= @exams_count %></h5>
        </div>
      </div>
    </div>

    <!-- Carte pour le nombre total de réservations en attente -->
    <div class="col-md-4">
      <div class="card text-center mb-4">
        <div class="card-header">
          Réservations en Attente
        </div>
        <div class="card-body">
          <h5 class="card-title"><%= @appointments_count %></h5>
        </div>
      </div>
    </div>
  </div>

  <!-- Section de gestion -->
  <div>
    <h3>Gestion</h3>
    <ul class="list-group">
      <li class="list-group-item"><%= link_to 'Gérer mes laboratoires', laboratories_path, class: 'btn btn-primary' %></li>
    </ul>
  </div>

</div>

elabo/app/views/laborantins/manage_laboratory.html.erb
<h1>Gérer <%= @laboratory.name %></h1>

<h2>Liste des examens</h2>
<ul>
  <% @laboratory.exams.each do |exam| %>
    <li><%= exam.name %> - <%= link_to 'Modifier', edit_exam_path(exam) %> | <%= link_to 'Supprimer', exam, method: :delete, data: { confirm: 'Êtes-vous sûr?' } %></li>
  <% end %>
</ul>

<%= link_to 'Ajouter un nouvel examen', new_laboratory_exam_path(laboratory_id: @laboratory.id) %>


<!-- <h1>Gérer mes laboratoires</h1>

<%= link_to 'Créer un nouveau laboratoire', new_laboratory_path, class: 'btn btn-primary mb-4' %>

<div class="row">
  <% @laboratories.each do |laboratory| %>
    <div class="col-md-4">
      <div class="card mb-4">
        <div class="card-body">
          <h5 class="card-title"><%= laboratory.name %></h5>
          <p class="card-text">
            <strong>Adresse :</strong> <%= laboratory.address %><br>
            <strong>Ville :</strong> <%= laboratory.city %><br>
            <strong>Email :</strong> <%= laboratory.email %>
          </p>

          <!-- Liens pour gérer le laboratoire (Modifier, Supprimer) -->
          <%= link_to 'Voir les examens', laboratory_exams_path(laboratory), class: 'btn btn-outline-primary' %> <!-- Lien mis à jour -->
          <%= link_to 'Modifier', edit_laboratory_path(laboratory), class: 'btn btn-outline-secondary' %>
          <%= link_to 'Supprimer', laboratory,data: { turbo: false, confirm: 'Êtes-vous sûr ?' }, class: 'btn btn-outline-danger' %>
        </div>
      </div>
    </div>
  <% end %>
</div> -->